project:
  type: website

website:
  page-navigation: true
  title: "Stream Gage Manual"
  site-url: "https://cawaterboarddatacenter.github.io/StreamGage-Manual/" 
  repo-url: https://github.com/CAWaterBoardDataCenter/StreamGage-Manual
  repo-actions: [edit, source, issue]
  favicon: images/logo-transparent.png  
  
  page-footer:
    right: "This manual is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By CA Water Board, 2024"

  sidebar:
    logo: "images/logo-transparent.png"
    favicon: images/logo-transparent.png
    align: center
    tools: 
      - icon: github
        href: https://github.com/CAWaterBoardDataCenter/StreamGage-Manual
        text: "Stream Gage Manual"
              
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome!
      - section: about/index.qmd
        text: Stream Gaging Basics
        contents:
          - about/howitworks.qmd
      - section: gage/index.qmd
        text: Gage Installation and Maintenance
        contents:
          - gage/siteselection.qmd 
      - section: flowmmt/index.qmd
        text: Flow Measurement
        contents:
          - flowmmt/siteselectionflow.qmd 
          - flowmmt/equipment.qmd
          - flowmmt/Flowtracker2.qmd
      - section: adcp/index.qmd
        text: ADCP Operations
        contents:
          - adcp/equipment_checklist.qmd
          - adcp/streamflow_gettingstarted.qmd
          - adcp/streamflow_field_measurement.qmd
          - adcp/streamflow_data_processing.qmd
          - adcp/bathymetry_gettingstarted.qmd
          - adcp/bathymetry_field_measurement.qmd
          - adcp/bathymetry_data_processing.qmd
      - section: ratings/index.qmd
        text: Rating Curves
        contents:
          - ratings/plottingandregression.qmd 
      - section: datamgmt/index.qmd
        text: Data Handling and Documentation
        contents:
         - datamgmt/datatostore.qmd
      - href: equipment.qmd
        text: Equipment
      - href: travel.qmd
        text: Travel
      - href: contribute.qmd
        text: Contributing
    
format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    fontsize: 1em
    grid:
      sidebar-width: 350px


filters:
  - include-files.lua
  - quarto

execute:
  freeze: auto