project:
  type: website

website:
  page-navigation: true
  title: "Stream Gage Manual"
  site-url: "https://cawaterboarddatacenter.github.io/swamp-manual/" 
  repo-url: https://github.com/CAWaterBoardDataCenter/StreamGage-Manual
  repo-actions: [edit, source, issue]
  favicon: images/logo-transparent.png  
  
  page-footer:
    right: "This manual is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By CA Water Board, 2024"

  sidebar:
    logo: "images/logo-transparent.png"
    favicon: images/logo-transparent.png
    align: center
    tools: 
      - icon: globe
        href: https://www.waterboards.ca.gov/water_issues/programs/swamp/
        text: "Stream Gaging"
      - icon: github
        href: https://cawaterboarddatacenter.github.io/swamp-manual/
        text: "Stream Gage Manual"
              
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome!
      - section: about/index.qmd
        text: About SWAMP
        contents:
          - about/lifecycle.qmd
          - about/contacts.qmd
      - section: culture/index.qmd
      - section: admin/index.qmd
        text: Administrative Goodies
        contents:
          - admin/onboarding.qmd
          - admin/tech.qmd
          - admin/training.qmd
          - admin/travel.qmd
          - admin/procurement.qmd
          - admin/offboarding.qmd
      - href: contribute.qmd
        text: Contibuting
      - href: inspiration.qmd
        text: Inspiration
    
format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    fontsize: 1em


filters:
  - include-files.lua
  - quarto

execute:
  freeze: auto