project:
  type: website

website:
  page-navigation: true
  title: "Stream Gage Manual"
  site-url: "https://cawaterboarddatacenter.github.io/stream_gaging/" 
  repo-url: https://github.com/CAWaterBoardDataCenter/StreamGage-Manual
  repo-actions: [edit, source, issue]
  favicon: images/logo-transparent.png  
  
  page-footer:
    right: "This manual is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By CA Water Board, 2024"

  sidebar:
    logo: "images/logo-transparent.png"
    favicon: images/logo-transparent.png
    align: center
    tools: 
      - icon: globe
        href: https://www.waterboards.ca.gov/water_issues/programs/swamp/
        text: "Stream Gaging"
      - icon: github
        href: https://github.com/CAWaterBoardDataCenter/StreamGage-Manual
        text: "Stream Gage Manual"
              
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome!
      - section: about/index.qmd
        text: Stream Gaging Basics
      - section: gage/index.qmd
        text: Gage Installation and Maintenance
      - section: flowmmt/index.qmd
        text: Flow Measurement
      - section: adcp/index.qmd
        text: ADCP Operations
        contents:
          - adcp/streamflow_gettingstarted.qmd
          - adcp/bathymetry_gettingstarted.qmd
          - adcp/equipment_checklist.qmd
          - adcp/measuring_streamflow.qmd
          - adcp/measuring_bathymetry.qmd
          - adcp/data_processing_streamflow.qmd
          - adcp/data_processing_bathymetry.qmd
      - section: ratings/index.qmd
        text: Rating Curves
      - section: datamgmt/index.qmd
        text: Data Handling and Documentation
      - section: admin/index.qmd
        text: Admin Stuff
        contents:
          - admin/contacts.qmd
          - admin/travel.qmd
          - admin/procurement.qmd
      - href: contribute.qmd
        text: Contibuting
      - href: inspiration.qmd
        text: Inspiration
    
format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    fontsize: 1em


filters:
  - include-files.lua
  - quarto

execute:
  freeze: autoAD`