# Contributing

## Who can contribute

We are seeking contributors to this manual. Please contact [Val Zimmer](https://github.com/vlzimmer) for more information.

## How we contribute

We develop the content using RStudio, build the book using [Quarto](https://quarto.org/) (via RStudio), and collaborate and publish using GitHub (also via RStudio).

*Note that there are other potential ways to contribute and if you are already familiar with Github, Quarto, and Markdown, you are welcome to use those methods.* Some notes on other methods are listed below:

-   The advantage to using R and RStudio is the ability to toggle between Source and Visual representation of the page, which means that editing the webpage is no more difficult than editing a word document.

-   The advantage of VsCode is seamless integration with Github.

### Setup via R and RStudio

To contribute, you must do the following, and it should only take about 20 minutes to complete:

1.  **Install R and RStudio**

    Both R and RStudio should be available in the Software Center (for Windows 10) or Company Portal (for Windows 11) -- if you don't see them in your Software Center/Company Portal or you have issues/questions during the instillation process, please send a request to the DIT HelpDesk and they can help you install them.

    Also see these [step by step instructions on how to install these programs](https://www.r4wrds.com/intro/m_install_r) -- you will only need to go through steps 1 and 2

    If you are new to R, it would also be helpful if you could review the [Getting Started Module](https://www.r4wrds.com/intro/m_getting_started.html) so you can begin to familiarize yourself with the fundamentals of the program.

2.  **Install Quarto**

    [Quarto download and install instructions](https://quarto.org/docs/getting-started/installation.html)

3.  **Create a GitHub Account**

    You will need to first [create your free personal account GitHub account](https://docs.github.com/en/get-started/signing-up-for-github/signing-up-for-a-new-github-account) using your waterboards email. You need to enable MFA and request access to the [Waterboard Github organization](https://github.com/CAWaterBoardDataCenter). A site administrator will invite you to join (please accept the invitation) and then we will invite you to join the team working on this website (please accept that one too).

    [Tips on choosing your username](https://happygitwithr.com/github-acct.html#username-advice)

4.  **Download and Install Git**

    Follow your operating system's normal [Git installation process](https://git-scm.com/downloads). Note: you will not see an application called Git listed but if the installation process completed it was likely successful, and we will confirm together.

5.  **Install Github Desktop (optional)**

    [Github desktop](https://desktop.github.com/download/) is a GUI that makes using Git easier for beginners. While it is not required, this is easier to learn than other methods. You will need to send a request to the DIT HelpDesk so they can install this free software.

### Setup via VsCode

TBD
