# selecting a good flow measurement site

There are a few factors to consider when choosing a site to take a flow measurement.

(Insert an image here)

## Features

**River Channel:** Look for an area where the channel is straight and uniform, supporting more laminar flow. Avoid sections where there are eddy's or areas of turbulence. 

This may be upstream of a "control," or a physical feature downstream that controls the flow in the channel segment above it. Examples are morphological units that constrict flow, such as stable riffles or bedrock outcroppings.

Channel banks should be stable and not easily susceptible to scouring, deposition, or migration. 

(Upload picture)

**Access:** This may end up being a more limiting factor, but the site chosen will need to be somewhere that can be accessed for data collection or for regular maintenance if a gauge is installed. 

## Other Considerations

Check for vegetation and algae growth, or any obstructions such as boulders, branches, or log jams. These can create sections of scouring and deposition, and create turbulence. 

Be aware of where tributaries connect either upstream or downstream of the chosen flow measurement site. 

