# Streamflow: Field Measurement

This section describes field measurements and procedures for the ADCP, which is used in deep or large rivers, or in smaller rivers with high flows. The ADCP requires water depths of at least 1 ft (2 or more feet is better). For streamflow measurements in wadeable streams (*not ADCP*), please see the [flow measurement section](../flowmmt/index.qmd).

Standard operating procedures, including (general) site selection, note-taking, safety, and data management, follows the same general principles for both ADCP measurements and measurements made by wading in the stream using a flowtracker or other similar instrument. Please refer to *add section here*.

This page deals with the specifics of collecting good streamflow measurements using the Sontek M9 using either a bridge or shore tether or driving the rQPOD motor.

Sontek has a [video training series](https://www.youtube.com/playlist?list=PLCbJJUmLdIBEZZWxyCGqeDhpF4T-Tyltn) on collecting streamflow data with the ADCP. Waterboards held a training day on 9/11/2024 and [recorded the pre-field training](https://cawaterboards.sharepoint.com/:v:/r/sites/WB-DWR-UASProgram/Shared%20Documents/06-Training/ADCP_and_Bathymetry/videos_from_training/Lab%20C_%20Streamflow%20Measurement%20with%20ADCP-20240911_090701-Meeting%20Recording.mp4?csf=1&web=1&e=pOBYyc).

## Pre-Trip Planning

-   install software
-   check equipment

## Site Selection

Please review the [Xylem site selection guide](https://cawaterboards.sharepoint.com/:b:/r/sites/WB-DWR-UASProgram/Shared%20Documents/01-Equipment/03-Manuals%20%26%20Instructions/Sontek_River_Surveyor_(ADCP)/adcp-site-selection-guide.pdf?csf=1&web=1&e=gFMd33) (also on [Xylem site](https://www.ysi.com/File%20Library/Documents/Guides/ADCP-Site-Selection-Guide.pdf)) to familiarize yourself with concepts such as uniform flow, turbulence, and magnetic interference.

test1

{{< https://www.youtube.com/embed/lWcFOu3bmqU?si=xYSK8IdnWCzQi8P_ >}}

test2

{{< video https://youtu.be/lWcFOu3bmqU?si=xYSK8IdnWCzQi8P_ width = "400" height = "300" >}}

## Tether or use the rQPOD motor?

### Tethering - how-to

### Motoring - how-to

## Data Collection

[preparing for measuring](https://www.youtube.com/watch?v=stV16mLqAUA&list=PLCbJJUmLdIBEZZWxyCGqeDhpF4T-Tyltn&index=4)

[Video on moving boat transect](https://www.youtube.com/watch?v=0rRt6OjTSGc&list=PLCbJJUmLdIBEZZWxyCGqeDhpF4T-Tyltn&index=5)
