# Streamflow: Data Processing

This section describes how to acquire and process streamflow data collected with the Sontek M9. Data management and rating curve generation is the same as that done for streamflow measurements collected by other methods. Please refer to *add section here*.

## Checking Data in the Office

[In office data review](https://www.youtube.com/watch?v=jRoFbFTokW0&list=PLCbJJUmLdIBEZZWxyCGqeDhpF4T-Tyltn&index=8)

[Webinar with questions answered](https://www.youtube.com/watch?v=ukb-B9e5OTY&list=PLCbJJUmLdIBEZZWxyCGqeDhpF4T-Tyltn&index=10)

### File types

The raw Sontek M9 files have the ending *.riv* and are collected and stored on the instrument itself. Data files that are transmitted via radio to a computer are replicates with an ending *.rivr*. Data processing should always use *.riv* files not *.rivr* files because the replicates are missing data lost in radio transmissions. The software allows some parameters to be changed post-field, and those changes are stored in *.wsp* files, so that the original raw files are never edited.

## Software Programs

The software used for collecting data and doing the bulk of the data processing is Sontek RiverSurveyor Live!. . The [USGS publishes free software](https://hydroacoustics.usgs.gov/movingboat/mbd_software.shtml) to help with ADCP data processing. Two recommended softwares are [QRev](https://hydroacoustics.usgs.gov/movingboat/QRev.shtml), which is used to compute discharge, and [extrap](https://www.usgs.gov/publications/extrap-software-assist-selection-extrapolation-methods-moving-boat-adcp-streamflow) (which might be embedded in QRev) to extrapolate measurements. USGS software requires data to be in Matlab format, which can be exported from the Sontek M9. (Future versions of the M9 may use newer software with these additional tools embedded.) *Add details here if you are processing data.*

## Training

Sontek has a [video training series](https://www.youtube.com/playlist?list=PLCbJJUmLdIBEZZWxyCGqeDhpF4T-Tyltn) on collecting streamflow data with the ADCP.

Waterboards held a training day on 9/11/2024 on the American River at the [Jim Jones pedestrian bridge near Sunrise](https://www.google.com/maps/place/Parking+Space/@38.6318805,-121.2704787,324m/data=!3m1!1e3!4m6!3m5!1s0x809add4070972437:0xc0e68ac138622df0!8m2!3d38.6317068!4d-121.2699568!16s%2Fg%2F11p5gp5kn6?entry=ttu&g_ep=EgoyMDI0MTAwMS4wIKXMDSoASAFQAw%3D%3D), about 3 miles downstream of the [USGS gage at Fair Oaks](https://waterdata.usgs.gov/monitoring-location/11446500/#parameterCode=00065&period=P7D&showMedian=false). We [collected data](https://cawaterboards.sharepoint.com/:f:/r/sites/WB-DWR-UASProgram/Shared%20Documents/06-Training/ADCP_and_Bathymetry/DATA_from_Training/2024_09_11_RiverSurveyor_Data?csf=1&web=1&e=41CDPX) on the training day that can be used for learning and following along with the RiverSurveyor Live! software, which can be installed by following instructions on the [Streamflow: Getting Started](streamflow_gettingstarted.qmd) page. We [recorded the pre-field training](https://cawaterboards.sharepoint.com/:v:/r/sites/WB-DWR-UASProgram/Shared%20Documents/06-Training/ADCP_and_Bathymetry/videos_from_training/Lab%20C_%20Streamflow%20Measurement%20with%20ADCP-20240911_090701-Meeting%20Recording.mp4?csf=1&web=1&e=pOBYyc) and the [post-field data processing](https://cawaterboards.sharepoint.com/sites/WB-DWR-UASProgram/_layouts/15/stream.aspx?id=%2Fsites%2FWB%2DDWR%2DUASProgram%2FShared%20Documents%2F06%2DTraining%2FADCP%5Fand%5FBathymetry%2Fvideos%5Ffrom%5Ftraining%2FLab%20D%20RiverSurveyorLive%20Streamflow%20%2D%20Data%20Processing%2D20241003%5F083326%2DMeeting%20Recording%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E1de8ce6f%2D90c5%2D4c10%2Da718%2Dde900aeb3d4f) for reference.

The USGS also has technical tips on adcp data collection and processing:

-   <https://www.usgs.gov/hydroacoustics/moving-boat-measurements>
